plugins { id 'com.android.application' }

android {
    namespace 'com.cybershield.ai'
    compileSdk 35
    defaultConfig {
        applicationId 'com.cybershield.ai'
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName '1.5'
    }

    flavorDimensions += "tier"
    productFlavors {
        safe {
            dimension "tier"
        }
        full {
            dimension "tier"
        }
    }

    signingConfigs {
        release {
            initWith signingConfigs.debug
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
